---
- name: Ensure {{ activemq_install_path }} exists
  ansible.builtin.file:
    path: "{{ activemq_install_path }}"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    mode: 0755
    state: directory

- name: Unarchive apache-activemq-{{ activemq_version }}-bin.tar.gz at {{ activemq_install_path }}
  ansible.builtin.unarchive:
    src: "http://archive.apache.org/dist/activemq/{{ activemq_version }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"
    dest: "{{ activemq_install_path }}"
    remote_src: true
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    creates: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}/bin"

- name: Fix parent folder permissions
  ansible.builtin.file:
    path: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    recurse: yes

- name: Deploy configuration file
  ansible.builtin.template:
    src: activemq.xml.j2
    dest: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}/conf/activemq.xml"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    mode: 0644
