---
- name: Check if apachemq is already installed
  ansible.builtin.stat:
    path: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}"
  register: is_installed

- name: Give up if installation already exists and not forced
  ansible.builtin.debug:
    msg: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }} already exists and will not be overwritten"
  when: is_installed.stat.exists and not activemq_force_install

- name: env | determine if {{ activemq_user }} exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ activemq_user }}"
    fail_key: false

- name: setup | create system user
  ansible.builtin.user:
    name: "{{ activemq_user }}"
    home: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}"
    create_home: no
    system: yes
    state: present
  when: getent_passwd[activemq_user] == none

- name: Install apachemq {{ activemq_version }}
  ansible.builtin.import_tasks: install.yml
  when: not is_installed.stat.exists or activemq_force_install
  notify: restart activemq
