- name: Check if apachemq is already installed
  stat:
    path: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}"
  register: is_installed

- name: Give up if installation already exists and not forced
  debug:
    msg: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }} already exists and will not be overwritten"
  when: is_installed.stat.exists and not activemq_force_install

- name: Install apachemq {{ activemq_version }}
  import_tasks: install.yml
  when: not is_installed.stat.exists or activemq_force_install

- name: Ensure ActiveMQ is running as {{ activemq_user }}
  shell: nohup ./activemq start </dev/null >/dev/null 2>&1 &
  args:
    chdir: "{{ activemq_install_path }}/apache-activemq-{{ activemq_version }}/bin/"
    executable: /bin/bash
  become: yes
  become_user: "{{ activemq_user }}"